version: '3.8'

services:
  # PostgreSQL - основная база данных
  postgres:
    image: postgres:16-alpine
    container_name: decanat-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: decanat
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Сервис аутентификации - управление пользователями и авторизацией
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: decanat-auth-service
    restart: unless-stopped
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=decanat
      - JWT_SECRET=your-secret-key
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8081:8081"

  # Сервис расписания - управление учебным расписанием
  schedule-service:
    build:
      context: ./schedule-service
      dockerfile: Dockerfile
    container_name: decanat-schedule-service
    restart: unless-stopped
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=decanat
      - AUTH_SERVICE_URL=http://auth-service:8081
    depends_on:
      postgres:
        condition: service_healthy
      auth-service:
        condition: service_started
    ports:
      - "8082:8082"

  # Сервис студенческих объединений - управление клубами и студенческими организациями
  club-service:
    build:
      context: ./club-service
      dockerfile: Dockerfile
    container_name: decanat-club-service
    restart: unless-stopped
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=decanat
      - AUTH_SERVICE_URL=http://auth-service:8081
    depends_on:
      postgres:
        condition: service_healthy
      auth-service:
        condition: service_started
    ports:
      - "8083:8083"

volumes:
  postgres-data: 