server:
  port: 8082
  timeout: 30s
  read_timeout: 15s
  write_timeout: 15s
  max_header_bytes: 1048576

database:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  dbname: decanat
  sslmode: disable
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 1h

auth:
  service_url: http://auth-service:8081
  timeout: 10s

jwt:
  secret: your-secret-key

telemetry:
  enabled: true
  service_name: schedule-service
  collector_url: otel-collector:4317

logging:
  level: info
  format: json 