services:
  # Общая база данных для хранения информации о пользователях (auth service)
  auth-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - ../auth-service/scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - decanat-network

  # База данных для сервиса абитуриентов
  applicant-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_APPLICANT_NAME}
    ports:
      - "5434:5432"
    volumes:
      - ../applicant-service/scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - decanat-network
  
  # База данных для сервиса расписания
  schedule-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_SCHEDULE_NAME}
    ports:
      - "5435:5432"
    volumes:
      - ../schedule-service/scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - decanat-network

  # База данных для сервиса студенческих объединений
  club-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_CLUB_NAME}
    ports:
      - "5436:5432"
    volumes:
      - ../club-service/scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - decanat-network

  # База данных для сервиса успеваемости
  performance-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_PERFORMANCE_NAME}
    ports:
      - "5437:5432"
    volumes:
      - ../performance-service/scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - decanat-network

  # База данных для сервиса социальной поддержки
  support-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_SUPPORT_NAME}
    ports:
      - "5438:5432"
    volumes:
      - ../support-service/scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - decanat-network

  # API Gateway
  api-gateway:
    build: ../api-gateway
    ports:
      - "${API_GATEWAY_PORT}:8080"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8080
      - APPLICANT_SERVICE_URL=http://applicant-service:8080
      - SCHEDULE_SERVICE_URL=http://schedule-service:8080
      - CLUB_SERVICE_URL=http://club-service:8080
      - PERFORMANCE_SERVICE_URL=http://performance-service:8080
      - SUPPORT_SERVICE_URL=http://support-service:8080
    depends_on:
      - auth-service
      - applicant-service
      - schedule-service
      - club-service
      - performance-service
      - support-service
    networks:
      - decanat-network

  # Сервис аутентификации
  auth-service:
    build: ../auth-service/backend
    ports:
      - "${AUTH_SERVICE_PORT}:8080"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=auth-db
      - DB_PORT=5432
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
    depends_on:
      - auth-db
    networks:
      - decanat-network

  # Сервис абитуриентов
  applicant-service:
    build: ../applicant-service/backend
    ports:
      - "${APPLICANT_SERVICE_PORT}:8080"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_APPLICANT_NAME}
      - DB_HOST=applicant-db
      - DB_PORT=5432
      - AUTH_SERVICE_URL=http://auth-service:8080
    depends_on:
      - applicant-db
      - auth-service
    networks:
      - decanat-network

  # Сервис расписания
  schedule-service:
    build: ../schedule-service/backend
    ports:
      - "${SCHEDULE_SERVICE_PORT}:8080"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_SCHEDULE_NAME}
      - DB_HOST=schedule-db
      - DB_PORT=5432
      - AUTH_SERVICE_URL=http://auth-service:8080
    depends_on:
      - schedule-db
      - auth-service
    networks:
      - decanat-network

  # Сервис студенческих объединений
  club-service:
    build: ../club-service/backend
    ports:
      - "${CLUB_SERVICE_PORT}:8080"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_CLUB_NAME}
      - DB_HOST=club-db
      - DB_PORT=5432
      - AUTH_SERVICE_URL=http://auth-service:8080
    depends_on:
      - club-db
      - auth-service
    networks:
      - decanat-network

  # Сервис успеваемости
  performance-service:
    build: ../performance-service/backend
    ports:
      - "${PERFORMANCE_SERVICE_PORT}:8080"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_PERFORMANCE_NAME}
      - DB_HOST=performance-db
      - DB_PORT=5432
      - AUTH_SERVICE_URL=http://auth-service:8080
    depends_on:
      - performance-db
      - auth-service
    networks:
      - decanat-network

  # Сервис социальной поддержки
  support-service:
    build: ../support-service/backend
    ports:
      - "${SUPPORT_SERVICE_PORT}:8080"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_SUPPORT_NAME}
      - DB_HOST=support-db
      - DB_PORT=5432
      - AUTH_SERVICE_URL=http://auth-service:8080
    depends_on:
      - support-db
      - auth-service
    networks:
      - decanat-network

# Общая сеть для взаимодействия сервисов
networks:
  decanat-network:
    driver: bridge
