server:
  port: 8081
  timeout: 30s
  read_timeout: 15s
  write_timeout: 15s
  max_header_bytes: 1048576

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: decanat
  sslmode: disable
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 1h

jwt:
  secret: your-secret-key
  access_expiration: 15m
  refresh_expiration: 24h

password:
  min_length: 8
  require_uppercase: true
  require_lowercase: true
  require_number: true
  require_special: true
  bcrypt_cost: 10

telemetry:
  enabled: false
  service_name: auth-service
  collector_url: otel-collector:4317

logging:
  level: debug
  format: console 