server:
  port: 8080
  timeout: 30s
  read_timeout: 15s
  write_timeout: 15s
  max_header_bytes: 1048576

services:
  auth_service:
    url: http://auth-service:8081
    timeout: 10s
  schedule_service:
    url: http://schedule-service:8082
    timeout: 10s
  club_service:
    url: http://club-service:8083
    timeout: 10s
  performance_service:
    url: http://performance-service:8084
    timeout: 10s
  applicant_service:
    url: http://applicant-service:8085
    timeout: 10s

jwt:
  secret: your-secret-key
  expiration: 24h

telemetry:
  enabled: true
  service_name: api-gateway
  collector_url: otel-collector:4317

logging:
  level: info
  format: json 